name: Testing

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repo
        uses: actions/checkout@v4
        with:
          path: '.'
          ref: main
          repository: luupanu/test-shared-workflow-calling-node-script
          sparse-checkout: |
            some-script.js
          sparse-checkout-cone-mode: false

      - name: Git clone Node script
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run a script
        run: node some-script.js
